### ISSUE TITLE
you do not mentioned login and password

### ISSUE THREAD

**Issue by 023PrashantSharma** [danamira/Larvael-Socket.IO-Chat-App#1]

**Comment by 023PrashantSharma** [comment]
sorry , my fault

**Comment by danamira** [comment]
Hi. Could you be more specific with what you mean by 'login and password'?
If you're referring to database credentials, with Laravel projects you create a new database on your machine and then place the credentials inside the `.env` file. Since the `.env` is ignored by Git/GitHub you can create a replica by chaning the name of `.env.example` to `.env`.
If you're talking about the application authentication, you can simply create a user in the route `/register` and login with your new user.
